global:
  clusterConfig:
    name: ""  # name to identify this cluster for events and metrics
  sysdig:
    accessKey: ""
    accessKeySecret: ""
    region: "us1"
  image:
    registry: quay.io
  kspm:
    deploy: false

agent:
  enabled: true

nodeAnalyzer:
  enabled: true

rapidResponse:
  enabled: false
  rapidResponse:
    passphrase: ""
    existingPassphraseSecret: ""
